import os

script_dir = os.path.dirname(os.path.abspath(__file__))
tex_file = os.path.join(script_dir, '..', 'tex', 'BEG.tex')

with open(tex_file, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    'dirkeciós': 'direkciós',
    'kellet ': 'kellett ',
    'módón': 'módon',
    'másikvégére': 'másik végére',
    'csapággyolyókat': 'csapágygolyókat',
    ' AZ ': ' Az ',
    'tartózó': 'tartozó',
    'legyen forgatónyomaték.': 'és a fellépő forgatónyomaték jól mérhető maradjon.',
    '(6,5 cm)': '(6,5 cm)',
    '(4,07 g)': '(4,07 g)',
    'belehelyztük': 'belehelyeztük',
    'súrlódásierők': 'súrlódási erők',
    'számatni': 'számtani',
    'szögelfordulását': 'szögelfordulást',
    'lejebb': 'lejjebb',
    'spriálrugójának': 'spirálrugójának',
    'szármtatható': 'származtatható',
    'Emellet': 'Emellett',
    'nyílván': 'nyilván',
    'tizedejegyek': 'tizedesjegyek',
    ' 0,005 g': ' 0,005 g',
    ' 0,05 cm': ' 0,05 cm',
    'alappján': 'alapján',
    'mérés hibát': 'mérési hibát',
    'rugó estében': 'rugó esetében',
    'Ámahhoz': 'Ahhoz',
    'másdodik': 'második',
    'amplitúúdó': 'amplitúdó-',
    'lehett': 'lehetett',
    'csillaőítási': 'csillapítási',
    'kelett': 'keltett',
    'kalibrálnunkk': 'kalibrálnunk',
    'viszgáltuk': 'vizsgáltuk',
    'idejét,annak': 'idejét, annak',
    '90^\circés': r'90^\circ és',
    'peródusidejét': 'periódusidejét',
    'adatinkat': 'adatainkat',
    '90^\circ-al': r'90^\circ-kal',
    'szármzó': 'származó',
    'mérésnélés': 'mérésnél és',
    'utolsó lengéshez tartozó periódusidőt': 'utolsó lengéshez tartozó amplitúdót',
    'rednszer': 'rendszer',
    'Ezenk kívül': 'Ezen kívül',
    'mödszerekkel': 'módszerekkel',
    'spirálrugú': 'spirálrugó',
    'tuljadonságait': 'tulajdonságait',
    'sgeítségével': 'segítségével',
    'állapítanoi': 'állapítani',
    'amódszerrel': 'a módszerrel',
    'ismerttehetetlenségi': 'ismert tehetetlenségi',
    'korognak': 'korongnak',
    'kisebbb': 'kisebb',
    'tehetetlneségi noymatéka': 'tehetetlenségi nyomatéka',
    'részcsap': 'rézcsap',
    'A eredményeket': 'Az eredményeket',
    'eredmémnyektől': 'eredményektől',
    'acélunk': 'a célunk',
    'gazoljuk': 'igazoljuk',
    'tehetetlenség noymatékú': 'tehetetlenségi nyomatékú',
    'Amnnyiben': 'Amennyiben',
    'jól mérük': 'jól mértünk',
    'azadatokra': 'az adatokra',
    'noymaték': 'nyomaték',
    'ezzela': 'ezzel a',
    'mega mérést': 'meg a mérést',
    'tomege': 'tömege',
    'mar sajnos': 'már sajnos',
    'vegigmerni': 'végigmérni',
    'igy': 'így',
    'ennel a lyuknal': 'ennél a lyuknál',
    'hasznaltuk': 'használtuk',
    'Ezutan': 'Ezután',
    'gorbet': 'görbét',
    'illesztesbol': 'illesztésből',
    'szarmazott': 'származott',
    'eredmenyeink': 'eredményeink',
    'egymashoz': 'egymáshoz',
    'kepest': 'képest',
    'elterest': 'eltérést',
    'Atlagolva': 'Átlagolva',
    'adodik': 'adódik',
    'tehetetlensegi': 'tehetetlenségi',
    'nyomatek': 'nyomaték',
    'ezután rugó': 'ezután a rugó',
    'megnyulás': 'megnyúlás',
    'mert adatok': 'mért adatok',
    'alapjan': 'alapján',
    'rugo ': 'rugó ',
    'tartomanyban': 'tartományban',
    'linearisan': 'lineárisan',
    'keplettel': 'képlettel',
    'kiszamoltuk': 'kiszámoltuk',
    'rugoallandot': 'rugóállandót',
    'meredekseget': 'meredekségét',
    'rugoallandora': 'rugóállandóra',
    'segitsegevel': 'segítségével',
    'rezkorongok nelkul': 'rézkorongok nélkül',
    'ket rezkoronggal': 'két rézkoronggal',
    'abrazoluk': 'ábrázoltuk',
    'szogsebesseget': 'szögsebességet',
    'tomegek': 'tömegek',
    'fuggvenyeben': 'függvényében',
    'alabbi': 'alábbi',
    'Igy ': 'Így ',
    'keszitettunk': 'készítettünk',
    'masik': 'másik',
    'fuggvenyekent': 'függvényeként',
    'abrazoltuk': 'ábrázoltuk',
    'illestettunk': 'illesztettünk',
    'Korfrekvencia': 'Körfrekvencia',
    'tomeg': 'tömeg',
    'Eleg szep': 'Elég szép',
    'masodik': 'második',
    'osszhangban': 'összhangban',
    'elmeleti': 'elméleti',
    'varakozasainkkal': 'várakozásainkkal',
    'Visszaszereltuk': 'Visszaszereltük',
    'es beallitottuk oket': 'és beállítottuk őket',
    'tavolsagra': 'távolságra',
    'ossztomege': 'össztömege',
    'beallitottuk a szukseges': 'beállítottuk a szükséges',
    'szelessegu': 'szélességű',
    'magassagu': 'magasságú',
    'alapszintu': 'alapszintű',
    'fuggvenygenerator': 'függvénygenerátor',
    'csatornajara': 'csatornájára',
    'T-eloszto': 'T-elosztó',
    'oszcilloszkopba': 'oszcilloszkópba',
    'szamitogephez': 'számítógéphez',
    'es a jelet A': 'és a jelet a',
    'elemeztuk': 'elemeztük',
    'masodpercenkent': 'másodpercenként',
    'elso feladatreszhez': 'első feladatrészhez',
    'leallitottuk': 'leállítottuk',
    'meghajtast': 'meghajtást',
    'megvizsgaltuk': 'megvizsgáltuk',
    'csillapitott': 'csillapított',
    'rezgest': 'rezgést',
    'tobb': 'több',
    'kis csillapitas eseten': 'kis csillapítás esetén',
    'bekapcsoltuk a gerjesztest': 'bekapcsoltuk a gerjesztést',
    'csillapitas eseten': 'csillapítás esetén',
    'surun': 'sűrűn',
    'korul': 'körül',
    'lepeskozzel': 'lépésközzel',
    'mertuk': 'mértük',
    'rezgesekre': 'rezgésekre',
    'szamitogeppel': 'számítógéppel',
    'fuggvenyt': 'függvényt',
    'illesztettunk': 'illesztettünk',
    'meghataroztuk': 'meghatároztuk',
    'rezges ': 'rezgés ',
    'amplitudojat': 'amplitúdóját',
    'Miutan': 'Miután',
    'kinyertuk': 'kinyertük',
    'amplitudokat': 'amplitúdókat',
    'elkeszitettuk': 'elkészítettük',
    'rezonanciagorbet': 'rezonanciagörbét',
    'rezonanciafrekvenciakat': 'rezonanciafrekvenciákat',
    'mindket csillapitasra': 'mindkét csillapításra',
    'kis es nagy': 'kis és nagy',
    'felismerheto': 'felismerhető',
    'rezonanciagorbek': 'rezonanciagörbék',
    'Mindket': 'Mindkét',
    'koruli': 'körüli',
    'erteket': 'értéket',
    'nincs tul tavol': 'nincs túl távol',
    r'sajatfrekvenciatol, (es kisebb) igy': r'sajátfrekvenciától (és kisebb), így',
    'elfogadhato': 'elfogadható',
    'eredmenyek': 'eredmények',
    'Vegul': 'Végül',
    'faziseltolast': 'fáziseltolást',
    'visszaszamoltuk ami szinten': 'visszaszámoltuk, ami szintén',
    'faziseltolasanak': 'fáziseltolásának',
    'grafikonjara': 'grafikonjára',
    'frekvencian': 'frekvencián',
    'faziskulonbseg': 'fáziskülönbség',
    'kozel': 'közel',
    'erosebb': 'erősebb',
    'csillapitasu': 'csillapítású',
    'gorbenel aho 1.2cm tavolsagra voltak a magnespofak': 'görbénél, ahol 1.2cm távolságra voltak a mágnespofák,',
    'probalkozasra': 'próbálkozásra',
    'semtudtuk': 'sem tudtuk',
    'tokeletesen': 'tökéletesen',
    'beallitani': 'beállítani',
    'utkozott': 'ütközött',
    'rud ': 'rúd ',
    'tobbi': 'többi',
    'alkatreszeve': 'alkatrészével',
    'magyarazhatja': 'magyarázhatja',
    'fura, es pontatlanabb alakjat': 'furcsa, és pontatlanabb alakját',
    'faziseltolas': 'fáziseltolás',
    'korulbelul': 'körülbelül',
    'rezonanciafrekvencian': 'rezonanciafrekvencián',
    'kovetkezik': 'következik',
    'mar ': 'már ',
    'burkolot': 'burkolót',
    'csucspontokra': 'csúcspontokra',
    'csillapitasi': 'csillapítási',
    'josagi': 'jósági',
    'tenyezo': 'tényező',
    'feltuntettuk': 'feltüntettük',
    'csillapitasnal': 'csillapításnál',
    'cillapitasi': 'csillapítási',
    'Valoban': 'Valóban',
    'elteroek': 'eltérőek',
    'modszer': 'módszer',
    'altal': 'által',
    'kulonosen': 'különösen',
    'tenyezore': 'tényezőre',
    'ertek': 'érték',
    'kozott': 'között',
    'relativ': 'relatív',
    'beallitottuk egy a gerjeszteshez kozeli frekvenciat es megfigyeltuk a lebegest': 'beállítottunk egy a gerjesztéshez közeli frekvenciát, és megfigyeltük a lebegést',
    'Lebegesre': 'lebegésre',
    'exponencialisan': 'exponenciálisan',
    'csokkeno': 'csökkenő',
    'szinuszgorbet': 'szinuszgörbét',
    'pedik': 'pedig',
    'Egyenesillesztéssel': 'Egyenes illesztéssel',
    'csillapitas ': 'csillapítás ',
    'amplitudojat': 'amplitúdóját',
    ' es ': ' és ',
    'rezgesekre': 'rezgésekre',
    'josagi ': 'jósági ',
    'Kg mm^2': r'\text{kg}\cdot\text{mm}^2',
    'Egy suly tomege': 'Egy súly tömege'
}

for old, new in replacements.items():
    text = text.replace(old, new)

with open(tex_file, 'w', encoding='utf-8') as f:
    f.write(text)

print('Kész! A BEG.tex fájlban kijavítottam a hibákat és pótoltam az ékezeteket.')
